# Generated by Django 2.0.5 on 2018-12-22 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('secret_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='mastermind.Code')),
            ],
        ),
        migrations.CreateModel(
            name='Peg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('black', '#000'), ('white', '#FFF'), ('#FF0000', 'red'), ('#0000FF', 'blue'), ('#00FF00', 'green'), ('#FFFF00', 'yellow')], max_length=10)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='code',
            name='pegs',
            field=models.ManyToManyField(to='mastermind.Peg'),
        ),
    ]
