# Generated by Django 2.0.5 on 2018-12-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.IntegerField(default=4),
        ),
    ]
