# Generated by Django 2.0.5 on 2018-12-22 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind', '0002_game_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackPeg',
            fields=[
                ('peg_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mastermind.Peg')),
            ],
            bases=('mastermind.peg',),
        ),
        migrations.CreateModel(
            name='GuessPeg',
            fields=[
                ('peg_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mastermind.Peg')),
            ],
            bases=('mastermind.peg',),
        ),
    ]
